# Generated by Django 3.1.7 on 2021-04-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superbody', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='age',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='gender',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='info',
            name='height',
        ),
        migrations.RemoveField(
            model_name='info',
            name='weight',
        ),
    ]
